sudo: required
services:
        - docker
         
before_install:
        - docker build -t lakshayangrish/docker-react -f Dockerfile.dev .
         
script:         
        - docker run lakshayangrish/docker-react npm run test -- --coverage
